### ISSUE TITLE
Finance module

### ISSUE THREAD

**Issue by gbaman** [gbaman/NI-Jam-Information-System#14]
A new module that will link into Google Sheets to handle Jam finance.
Google Sheets will be used as the backend, with 2 tables.

Split into 2 sections

### Expenses
- [x] Volunteers can submit expenses (upload photo with cost, date and paypal email address)
- [x] Trustees can view all expenses.
- [x] Trustees can approve expenses or reject (with a reason attached).
- [x] Volunteers can see the status of their expenses.

### Ledger
- [x] Trustees can import CSV file which auto builds the ledger.
- [x] Trustees can add items to the ledger (upload photo, receipt date, supplier, description, paid by, category).
- [x] Trustees can approve payments in the ledger (mainly the treasurer).
- [x] Trustees can match an expense into the ledger.

This module is being devolved on the [finance](https://github.com/gbaman/NI-Jam-Information-System/tree/finance) branch.

**Comment by gbaman** [comment]
This module is now complete and is in testing on the live site.

**Comment by JamesMatchett** [comment]
Need a tester @gbaman ?

**Comment by gbaman** [comment]
Thanks for the offer @JamesMatchett , but we are already live. Plus, not much of it can be tested outside the trustees as live data now in it.
So far *crosses fingers* all seems to work. But big test will be when Lucy does her first pass through over the next month. What could possibly go wrong...

**Comment by gbaman** [comment]
Finance module now merged in to master
https://github.com/gbaman/NI-Jam-Information-System/commit/d42a6d485ba819f72542df3874025cb0ad4497f4
