### ISSUE TITLE
Wrangler printout

### ISSUE THREAD

**Issue by gbaman** [gbaman/NI-Jam-Information-System#2]
To help support wranglers do their job of checking people are all in the rooms they are meant to be, we need an auto generated checklist that can be printed at 12:45 at each Jam, once all the NIJIS signups have been completed.

- [x] A button that generates a printable list of rooms in use with workshops and volunteers checkboxes.
- [x] Once inventory system is up and working, the wrangler list also includes equipment move instructions if any between workshops on the day.
- [x] A button that includes a list of equipment needed for each workshop (for the Friday night).
- [x] In addition, perhaps shows worksheets needed somehow?

**Comment by CaolanMcKendry** [comment]
Could we also have a list of what attendees are in each workshop?

**Comment by gbaman** [comment]
Well @CaolanMcKendry, not sure that is something really for the wrangler sheet, as the wrangler doesn't use that info? They are  listed in the manage workshops in Jam page

**Comment by CaolanMcKendry** [comment]
Fair point, just thought it would make sense for wranglers to ensure that attendees are also where they're supposed to be
